source ~/.bash/customs/general.bash
source ~/.bash/customs/git.bash
source ~/.bash/customs/rails.bash
source ~/.bash/customs/custom.bash
source ~/.bash/customs/prompt.bash
source ~/.bash/customs/navigation.bash
source ~/.bash/customs/erlang.bash
source ~/.bash/customs/tmux.bash
source ~/.bash/customs/postgres.bash
source ~/.bash/customs/emacs.bash
